import { test, expect } from '@playwright/test';

test('prepara PWA, conclui sem carga offline, recarrega e sincroniza uma vez', async ({ page, context }) => {
  const email = process.env.TREINOS_TEST_EMAIL;
  const password = process.env.TREINOS_TEST_PASSWORD;
  if (!email || !password) throw Error('Configure credenciais exclusivas do ambiente de teste.');
  await expect.poll(async () => (await page.request.get('/api/health/ready')).status(), { timeout: 30000 }).toBe(200);
  await page.goto('/');
  await page.getByLabel('E-mail', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Vamos treinar?' })).toBeVisible();
  await page.getByRole('button', { name: 'Preparar offline', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Offline preparado');
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await page.reload();
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true);
  await context.setOffline(true);
  await page.reload();
  await page.getByRole('button', { name: 'Começar treino', exact: true }).click();
  await page.locator('select').first().selectOption({ index: 1 });
  await page.getByRole('button', { name: 'Iniciar treino', exact: true }).click();
  await page.getByRole('button', { name: 'Marcar todos como realizados' }).click();
  await page.getByRole('button', { name: 'Concluir treino', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Novo registro' })).toBeVisible();
  await page.getByRole('button', { name: 'Histórico', exact: true }).click();
  await expect(page.locator('.list-row').first()).toContainText('Concluído');
  const count = await page.locator('.list-row').count();
  await page.reload();
  await expect(page.locator('.list-row')).toHaveCount(count);
  await expect(page.locator('.sync-pill')).not.toHaveText('0 pendências');
  await page.close();
  page = await context.newPage();
  await page.goto('/history');
  await expect(page.locator('.list-row')).toHaveCount(count);
  await context.setOffline(false);
  await page.locator('.header-right button').click();
  await page.getByRole('button', { name: 'Sincronizar agora', exact: true }).click();
  await expect(page.locator('.sync-pill')).toHaveText('0 pendências', { timeout: 30000 });
  await page.getByRole('button', { name: 'Sincronizar agora', exact: true }).click();
  await page.getByRole('button', { name: 'Histórico', exact: true }).click();
  await expect(page.locator('.list-row')).toHaveCount(count);
});

test('modo detalhado conclui uma série sem inventar carga', async ({ page, context }) => {
  await page.goto('/');
  await page.getByLabel('E-mail', { exact: true }).fill(process.env.TREINOS_TEST_EMAIL!);
  await page.getByLabel('Senha', { exact: true }).fill(process.env.TREINOS_TEST_PASSWORD!);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('button', { name: 'Preparar offline', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Offline preparado');
  await context.setOffline(true);
  await page.getByRole('button', { name: 'Começar treino', exact: true }).click();
  await page.locator('select').nth(1).selectOption('detailed');
  await page.getByLabel('Adicionar exercício', { exact: true }).selectOption({ index: 1 });
  await page.getByRole('button', { name: 'Adicionar exercício', exact: true }).click();
  await page.getByRole('button', { name: 'Iniciar treino', exact: true }).click();
  await page.getByRole('button', { name: 'Adicionar série', exact: true }).click();
  await page.getByLabel('Repetições', { exact: true }).fill('10');
  await page.getByRole('button', { name: 'Concluir série', exact: true }).click();
  await expect(page.locator('.set-editor')).toContainText('concluída');
  await page.getByRole('button', { name: 'Concluir treino', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Novo registro' })).toBeVisible();
  await context.setOffline(false);
  await page.locator('.header-right button').click();
  await page.getByRole('button', { name: 'Sincronizar agora', exact: true }).click();
  await expect(page.locator('.sync-pill')).toHaveText('0 pendências');
  const data = await (await page.request.get('/api/sync/bootstrap')).json();
  const session = data.sessions.find((s: { workoutNameSnapshot: string }) => s.workoutNameSnapshot === 'Treino avulso');
  expect(session.status).toBe('completed');
  expect(session.exercises[0].sets[0].repetitions).toBe(10);
  expect(session.exercises[0].sets[0].loadKg).toBeNull();
});
