export type Account = {
  id: string;
  displayName: string;
  email: string;
  role: "administrator" | "common";
  mustChangePassword: boolean;
  timeZone: string;
};
export type Exercise = {
  id: string;
  name: string;
  muscleGroup: string;
  equipment?: string;
  measurementType: "reps" | "duration";
  loadKind: string;
  loadBasis: string;
  instructions?: string;
  rowVersion: number;
};
export type TemplateItem = {
  id: string;
  exerciseId: string;
  position: number;
  targetSets: number;
  repsMin?: number;
  repsMax?: number;
  durationSecondsMin?: number;
  durationSecondsMax?: number;
  restSecondsMin: number;
  restSecondsMax: number;
  repetitionScope: "total" | "per_side";
  alternatives: string[];
  restScope?: string;
  notes?: string;
};
export type Template = {
  id: string;
  code: string;
  name: string;
  position: number;
  notes?: string;
  items: TemplateItem[];
  rowVersion: number;
};
export type Plan = {
  id: string;
  name: string;
  description?: string;
  templates: Template[];
  rowVersion: number;
  instructions?: string;
  introductorySets?: number;
};
export type SetEntry = {
  id: string;
  setNumber: number;
  side: "both" | "left" | "right";
  repetitions: number | null;
  durationSeconds: number | null;
  loadKg: number | null;
  rir: number | null;
  isWarmup: boolean;
  isCompleted: boolean;
};
export type ExerciseEntry = {
  id: string;
  exerciseId: string;
  position: number;
  exerciseNameSnapshot: string;
  measurementTypeSnapshot: "reps" | "duration";
  loadKindSnapshot: string;
  loadBasisSnapshot: string;
  repetitionScopeSnapshot: "total" | "per_side";
  completionStatus: "planned" | "completed" | "skipped";
  sets: SetEntry[];
  equipmentSnapshot?: string;
  instructionsSnapshot?: string;
  targetSetsSnapshot?: number;
  repsMinSnapshot?: number;
  repsMaxSnapshot?: number;
  durationMinSnapshot?: number;
  durationMaxSnapshot?: number;
  restMinSnapshot?: number;
  restMaxSnapshot?: number;
  restScopeSnapshot?: string;
  prescriptionNotesSnapshot?: string;
  notes?: string;
};
export type Session = {
  id: string;
  templateId: string | null;
  workoutNameSnapshot: string;
  performedOn: string;
  timeZoneSnapshot: string;
  status: "in_progress" | "completed" | "cancelled";
  recordingMode: "quick" | "detailed";
  notes: string | null;
  exercises: ExerciseEntry[];
  rowVersion: number;
  deleted?: boolean;
  planNameSnapshot?: string;
  isIntroductoryWeek?: boolean;
  planInstructionsSnapshot?: string;
  startedAtUtc?: string;
  endedAtUtc?: string;
  completedAtUtc?: string;
};
export type Operation = {
  operationId: string;
  deviceId: string;
  schemaVersion: 1;
  entityId: string;
  kind: "create" | "replace" | "delete";
  baseVersion: number;
  snapshot: Session | null;
  state: "pending" | "sending" | "conflict" | "failed" | "auth_required";
  attempted: boolean;
  error?: string;
  owner: string;
  createdAt: number;
  attempts?: number;
  retryAt?: number;
};
export type Bootstrap = {
  revision: number;
  exercises: Exercise[];
  plans: Plan[];
  sessions: Session[];
  historyDays: number;
};
export type Conflict = {
  entityId: string;
  version: number;
  server: Session | null;
  deleted: boolean;
};
export type SyncPage = {
  nextCursor: number;
  hasMore: boolean;
  observedRevision: number;
  changes: {
    revision: number;
    entityType: string;
    entityVersion?: number | null;
    entityId: string | null;
    changeKind: string;
    payloadJson: string | null;
  }[];
};
