-- 001_schema_treinos.sql
-- Esquema inicial de referência: MariaDB 11.8, InnoDB, UTF-8.
-- Aplicar UMA VEZ em banco vazio, selecionado pelo cliente mariadb.
-- O migrator da aplicação deve controlar versão/checksum. DDL causa commits
-- implícitos no MariaDB: não prometa rollback integral desta migração.
-- Não cria banco, usuário de acesso ou conta do aplicativo.
-- Sessões de banco e datas técnicas devem usar UTC.
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE app_users (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_name VARCHAR(256) NOT NULL,
    normalized_user_name VARCHAR(256) COLLATE utf8mb4_bin NOT NULL,
    email VARCHAR(256) NOT NULL,
    normalized_email VARCHAR(256) COLLATE utf8mb4_bin NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    password_hash VARCHAR(512) NOT NULL,
    security_stamp CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    concurrency_stamp CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    email_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    lockout_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    lockout_end_utc DATETIME(6) NULL,
    access_failed_count INT UNSIGNED NOT NULL DEFAULT 0,
    time_zone VARCHAR(64) NOT NULL DEFAULT 'America/Sao_Paulo',
    created_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_normalized_username (normalized_user_name),
    UNIQUE KEY uq_users_normalized_email (normalized_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE exercises (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    seed_code VARCHAR(100) NULL,
    name VARCHAR(160) NOT NULL,
    muscle_group VARCHAR(80) NOT NULL,
    equipment VARCHAR(120) NULL,
    instructions TEXT NULL,
    measurement_type VARCHAR(12) NOT NULL DEFAULT 'reps',
    load_kind VARCHAR(12) NOT NULL DEFAULT 'external',
    load_basis VARCHAR(20) NOT NULL DEFAULT 'total',
    load_unit CHAR(2) NOT NULL DEFAULT 'kg',
    deleted_at_utc DATETIME(6) NULL,
    created_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_exercises_owner_id (user_id, id),
    CONSTRAINT fk_exercises_owner FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    UNIQUE KEY uq_exercises_seed (user_id, seed_code),
    KEY ix_exercises_catalog (user_id, deleted_at_utc, name),
    CONSTRAINT ck_exercise_measure CHECK (measurement_type IN ('reps','duration')),
    CONSTRAINT ck_exercise_load_kind CHECK (load_kind IN ('external','bodyweight','assisted')),
    CONSTRAINT ck_exercise_load_basis CHECK (load_basis IN ('total','per_hand','machine_display','added_weight')),
    CONSTRAINT ck_exercise_unit CHECK (load_unit = 'kg')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workout_plans (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    seed_code VARCHAR(100) NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT NULL,
    duration_weeks SMALLINT UNSIGNED NULL,
    introductory_sets SMALLINT UNSIGNED NULL,
    rir_min TINYINT UNSIGNED NULL,
    rir_max TINYINT UNSIGNED NULL,
    warmup_seconds_min INT UNSIGNED NULL,
    warmup_seconds_max INT UNSIGNED NULL,
    cardio_seconds_min INT UNSIGNED NULL,
    cardio_seconds_max INT UNSIGNED NULL,
    instructions TEXT NULL,
    deleted_at_utc DATETIME(6) NULL,
    created_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_plans_owner_id (user_id, id),
    CONSTRAINT fk_plans_owner FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    UNIQUE KEY uq_plans_seed (user_id, seed_code),
    CONSTRAINT ck_plan_weeks CHECK (duration_weeks IS NULL OR duration_weeks > 0),
    CONSTRAINT ck_plan_intro CHECK (introductory_sets IS NULL OR introductory_sets > 0),
    CONSTRAINT ck_plan_rir CHECK ((rir_min IS NULL AND rir_max IS NULL) OR (rir_min IS NOT NULL AND rir_max IS NOT NULL AND rir_min <= rir_max AND rir_max <= 10)),
    CONSTRAINT ck_plan_warmup CHECK ((warmup_seconds_min IS NULL AND warmup_seconds_max IS NULL) OR (warmup_seconds_min IS NOT NULL AND warmup_seconds_max IS NOT NULL AND warmup_seconds_min <= warmup_seconds_max)),
    CONSTRAINT ck_plan_cardio CHECK ((cardio_seconds_min IS NULL AND cardio_seconds_max IS NULL) OR (cardio_seconds_min IS NOT NULL AND cardio_seconds_max IS NOT NULL AND cardio_seconds_min <= cardio_seconds_max))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workout_templates (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(120) NOT NULL,
    suggested_iso_weekday TINYINT UNSIGNED NULL,
    position SMALLINT UNSIGNED NOT NULL,
    notes TEXT NULL,
    deleted_at_utc DATETIME(6) NULL,
    created_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_templates_owner_id (user_id, id),
    CONSTRAINT fk_templates_owner FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    UNIQUE KEY uq_templates_code (user_id, plan_id, code),
    CONSTRAINT fk_templates_plan FOREIGN KEY (user_id, plan_id) REFERENCES workout_plans (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_template_weekday CHECK (suggested_iso_weekday IS NULL OR suggested_iso_weekday BETWEEN 1 AND 7),
    CONSTRAINT ck_template_position CHECK (position > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workout_template_items (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    template_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    exercise_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    position SMALLINT UNSIGNED NOT NULL,
    target_sets SMALLINT UNSIGNED NOT NULL,
    reps_min SMALLINT UNSIGNED NULL,
    reps_max SMALLINT UNSIGNED NULL,
    duration_seconds_min INT UNSIGNED NULL,
    duration_seconds_max INT UNSIGNED NULL,
    repetition_scope VARCHAR(12) NOT NULL DEFAULT 'total',
    rest_seconds_min SMALLINT UNSIGNED NOT NULL,
    rest_seconds_max SMALLINT UNSIGNED NOT NULL,
    rest_scope VARCHAR(20) NOT NULL DEFAULT 'after_set',
    notes TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_template_items_owner_id (user_id, id),
    CONSTRAINT fk_template_items_owner FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    UNIQUE KEY uq_template_item_position (user_id, template_id, position),
    CONSTRAINT fk_template_item_template FOREIGN KEY (user_id, template_id) REFERENCES workout_templates (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_template_item_exercise FOREIGN KEY (user_id, exercise_id) REFERENCES exercises (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_template_item_positive CHECK (position > 0 AND target_sets > 0),
    CONSTRAINT ck_template_item_measure CHECK ((reps_min IS NOT NULL AND reps_max IS NOT NULL AND reps_min > 0 AND reps_max >= reps_min AND duration_seconds_min IS NULL AND duration_seconds_max IS NULL) OR (reps_min IS NULL AND reps_max IS NULL AND duration_seconds_min IS NOT NULL AND duration_seconds_max IS NOT NULL AND duration_seconds_min > 0 AND duration_seconds_max >= duration_seconds_min)),
    CONSTRAINT ck_template_item_scope CHECK (repetition_scope IN ('total','per_side')),
    CONSTRAINT ck_template_item_rest_scope CHECK (rest_scope IN ('after_set','after_both_sides')),
    CONSTRAINT ck_template_item_rest CHECK (rest_seconds_min <= rest_seconds_max)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workout_item_alternatives (
    user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    template_item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    exercise_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PRIMARY KEY (user_id, template_item_id, exercise_id),
    CONSTRAINT fk_alternative_item FOREIGN KEY (user_id, template_item_id) REFERENCES workout_template_items (user_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_alternative_exercise FOREIGN KEY (user_id, exercise_id) REFERENCES exercises (user_id, id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workout_sessions (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    template_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    plan_name_snapshot VARCHAR(160) NULL,
    workout_name_snapshot VARCHAR(160) NOT NULL,
    performed_on DATE NOT NULL,
    time_zone_snapshot VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'in_progress',
    recording_mode VARCHAR(12) NOT NULL DEFAULT 'detailed',
    is_introductory_week BOOLEAN NOT NULL DEFAULT FALSE,
    plan_instructions_snapshot TEXT NULL,
    started_at_utc DATETIME(6) NULL,
    ended_at_utc DATETIME(6) NULL,
    completed_at_utc DATETIME(6) NULL,
    notes TEXT NULL,
    client_request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    deleted_at_utc DATETIME(6) NULL,
    created_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sessions_owner_id (user_id, id),
    CONSTRAINT fk_sessions_owner FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    UNIQUE KEY uq_session_request (user_id, client_request_id),
    KEY ix_session_history (user_id, deleted_at_utc, status, performed_on, id),
    CONSTRAINT fk_session_template FOREIGN KEY (user_id, template_id) REFERENCES workout_templates (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_session_status CHECK (status IN ('in_progress','completed','cancelled')),
    CONSTRAINT ck_session_mode CHECK (recording_mode IN ('quick','detailed')),
    CONSTRAINT ck_session_times CHECK (started_at_utc IS NULL OR ended_at_utc IS NULL OR ended_at_utc >= started_at_utc),
    CONSTRAINT ck_session_completed CHECK ((status = 'completed' AND completed_at_utc IS NOT NULL) OR (status <> 'completed' AND completed_at_utc IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE session_exercises (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    session_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    exercise_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    position SMALLINT UNSIGNED NOT NULL,
    exercise_name_snapshot VARCHAR(160) NOT NULL,
    equipment_snapshot VARCHAR(120) NULL,
    instructions_snapshot TEXT NULL,
    measurement_type_snapshot VARCHAR(12) NOT NULL,
    load_kind_snapshot VARCHAR(12) NOT NULL,
    load_basis_snapshot VARCHAR(20) NOT NULL,
    load_unit_snapshot CHAR(2) NOT NULL,
    repetition_scope_snapshot VARCHAR(12) NOT NULL,
    target_sets_snapshot SMALLINT UNSIGNED NULL,
    reps_min_snapshot SMALLINT UNSIGNED NULL,
    reps_max_snapshot SMALLINT UNSIGNED NULL,
    duration_min_snapshot INT UNSIGNED NULL,
    duration_max_snapshot INT UNSIGNED NULL,
    rest_min_snapshot SMALLINT UNSIGNED NULL,
    rest_max_snapshot SMALLINT UNSIGNED NULL,
    rest_scope_snapshot VARCHAR(20) NULL,
    prescription_notes_snapshot TEXT NULL,
    completion_status VARCHAR(12) NOT NULL DEFAULT 'planned',
    notes TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_session_exercises_owner_id (user_id, id),
    CONSTRAINT fk_session_exercises_owner FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    UNIQUE KEY uq_session_exercise_position (user_id, session_id, position),
    KEY ix_session_exercise_progress (user_id, exercise_id, session_id),
    CONSTRAINT fk_session_exercise_session FOREIGN KEY (user_id, session_id) REFERENCES workout_sessions (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_session_exercise_catalog FOREIGN KEY (user_id, exercise_id) REFERENCES exercises (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_session_exercise_status CHECK (completion_status IN ('planned','completed','skipped')),
    CONSTRAINT ck_session_exercise_measure CHECK (measurement_type_snapshot IN ('reps','duration')),
    CONSTRAINT ck_session_exercise_load_kind CHECK (load_kind_snapshot IN ('external','bodyweight','assisted')),
    CONSTRAINT ck_session_exercise_basis CHECK (load_basis_snapshot IN ('total','per_hand','machine_display','added_weight')),
    CONSTRAINT ck_session_exercise_unit CHECK (load_unit_snapshot = 'kg'),
    CONSTRAINT ck_session_exercise_scope CHECK (repetition_scope_snapshot IN ('total','per_side')),
    CONSTRAINT ck_session_exercise_position CHECK (position > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE session_sets (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    session_exercise_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    set_number SMALLINT UNSIGNED NOT NULL,
    side VARCHAR(8) NOT NULL DEFAULT 'both',
    repetitions SMALLINT UNSIGNED NULL,
    duration_seconds INT UNSIGNED NULL,
    load_kg DECIMAL(7,2) NULL,
    rir TINYINT UNSIGNED NULL,
    is_warmup BOOLEAN NOT NULL DEFAULT FALSE,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_sets_owner_id (user_id, id),
    CONSTRAINT fk_sets_owner FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    UNIQUE KEY uq_set_number_side (user_id, session_exercise_id, set_number, side),
    CONSTRAINT fk_set_session_exercise FOREIGN KEY (user_id, session_exercise_id) REFERENCES session_exercises (user_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_set_side CHECK (side IN ('both','left','right')),
    CONSTRAINT ck_set_number CHECK (set_number > 0),
    CONSTRAINT ck_set_reps CHECK (repetitions IS NULL OR repetitions > 0),
    CONSTRAINT ck_set_duration CHECK (duration_seconds IS NULL OR duration_seconds > 0),
    CONSTRAINT ck_set_load CHECK (load_kg IS NULL OR load_kg >= 0),
    CONSTRAINT ck_set_rir CHECK (rir IS NULL OR rir BETWEEN 0 AND 10),
    CONSTRAINT ck_set_one_metric CHECK (repetitions IS NULL OR duration_seconds IS NULL),
    CONSTRAINT ck_set_completed_metric CHECK (is_completed = FALSE OR repetitions IS NOT NULL OR duration_seconds IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE seed_imports (
    user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    seed_key VARCHAR(100) NOT NULL,
    imported_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (user_id, seed_key),
    CONSTRAINT fk_seed_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
