import {beforeEach,describe,it,expect,vi} from 'vitest';
import 'fake-indexeddb/auto';
import {IDBFactory,IDBKeyRange} from 'fake-indexeddb';
import {webcrypto} from 'node:crypto';
import type {Session,Bootstrap} from '../src/shared/types';
let store:typeof import('../src/offline/store');
const user='user-a';const device='device-a';
function session():Session{return{id:crypto.randomUUID(),templateId:null,workoutNameSnapshot:'Teste',performedOn:new Date().toISOString().slice(0,10),timeZoneSnapshot:'America/Sao_Paulo',status:'in_progress',recordingMode:'quick',notes:null,exercises:[],rowVersion:0}}
function bootstrap(sessions:Session[]):Bootstrap{return{revision:1,historyDays:90,exercises:[],plans:[],sessions}}
beforeEach(async()=>{vi.resetModules();Object.assign(globalThis,{indexedDB:new IDBFactory(),IDBKeyRange,sessionStorage:{getItem:vi.fn(),setItem:vi.fn(),removeItem:vi.fn()}});store=await import('../src/offline/store')});
describe('fila durável de sessões',()=>{
  it('coalesce antes da tentativa e congela a intenção após enviar',async()=>{const s=session();await store.saveSession(user,s,device);const first=(await store.pending(user))[0];await store.saveSession(user,{...s,notes:'editado'},device);const updated=(await store.pending(user))[0];expect(updated.operationId).not.toBe(first.operationId);expect(updated.kind).toBe('create');await store.markSending(user,updated);await store.saveSession(user,{...s,notes:'nova edição'},device);const queue=await store.pending(user);expect(queue).toHaveLength(2);expect(queue[0].snapshot?.notes).toBe('editado');expect(queue[1].snapshot?.notes).toBe('nova edição');await store.acknowledge(user,queue[0],1);const next=(await store.pending(user))[0];expect(next.kind).toBe('replace');expect(next.baseVersion).toBe(1);expect((await store.sessions(user))[0].notes).toBe('nova edição')});
  it('cancelar criação nunca enviada não envia delete',async()=>{const s=session();await store.saveSession(user,s,device);await store.saveSession(user,{...s,deleted:true},device);expect(await store.pending(user)).toHaveLength(0);expect(await store.sessions(user)).toHaveLength(0)});
  it('delete depois de tentativa incerta recupera o ACK antes de excluir',async()=>{const s=session();await store.saveSession(user,s,device);const op=(await store.pending(user))[0];await store.markSending(user,op);await store.saveSession(user,{...s,deleted:true},device);expect((await store.pending(user)).map(x=>x.kind)).toEqual(['create','delete']);await store.acknowledge(user,op,1);expect((await store.pending(user))[0].baseVersion).toBe(1)});
  it('snapshot e troca de conta preservam partições e pendências',async()=>{const a=session(),b=session();await store.saveSession(user,a,device);await store.saveSession('user-b',b,device);await store.saveBootstrap(user,bootstrap([]));expect(await store.sessions(user)).toHaveLength(1);expect(await store.sessions('user-b')).toHaveLength(1);expect(await store.pending(user)).toHaveLength(1)});
  it('receber tombstone remove somente cópia sem pendências e avança cursor',async()=>{const s={...session(),rowVersion:1};await store.saveBootstrap(user,bootstrap([s]));await store.applyChanges(user,{nextCursor:2,observedRevision:2,hasMore:false,changes:[{revision:2,entityId:s.id,entityType:'session',changeKind:'delete',payloadJson:null}]});expect(await store.sessions(user)).toHaveLength(0);expect((await store.meta(user))?.cursor).toBe(2)});
  it('conflito preserva local e reaplica com novo ID e base atual',async()=>{const s={...session(),rowVersion:1};await store.saveBootstrap(user,bootstrap([s]));await store.saveSession(user,{...s,notes:'local'},device);const op=(await store.pending(user))[0];await store.saveConflict(user,op,{entityId:s.id,version:2,deleted:false,server:{...s,notes:'servidor',rowVersion:2}});await store.resolveConflict(user,s.id,'local',device);const next=(await store.pending(user))[0];expect(next.operationId).not.toBe(op.operationId);expect(next.baseVersion).toBe(2);expect(next.snapshot?.notes).toBe('local');expect(await store.conflicts(user)).toHaveLength(0)});
  it('conflito com exclusão não descarta a fila ao rejeitar reaplicação',async()=>{const s={...session(),rowVersion:1};await store.saveSession(user,s,device);const op=(await store.pending(user))[0];await store.saveConflict(user,op,{entityId:s.id,version:2,deleted:true,server:null});await expect(store.resolveConflict(user,s.id,'local',device)).rejects.toThrow();expect(await store.pending(user)).toHaveLength(1);expect(await store.conflicts(user)).toHaveLength(1)});
  it('lease impede dois emissores e só o proprietário libera',async()=>{expect(await store.acquireLease(user,'tab-a')).toBe(true);expect(await store.acquireLease(user,'tab-b')).toBe(false);await store.releaseLease(user,'tab-b');expect(await store.acquireLease(user,'tab-b')).toBe(false);await store.releaseLease(user,'tab-a');expect(await store.acquireLease(user,'tab-b')).toBe(true)});
  it('um formulário com versão antiga usa a versão confirmada no armazenamento',async()=>{const s=session();await store.saveSession(user,s,device);await store.acknowledge(user,(await store.pending(user))[0],1);await store.saveSession(user,{...s,notes:'depois do ACK'},device);expect((await store.pending(user))[0].baseVersion).toBe(1);expect((await store.pending(user))[0].kind).toBe('replace')});
  it('reabre a conta preparada sem sessionStorage e bloqueia após sair',async()=>{const account={id:user,displayName:'A',email:'a@example.invalid',role:'common' as const,mustChangePassword:false,timeZone:'America/Sao_Paulo'};await store.saveAccount(account);expect(await store.activeAccount()).toEqual(account);await store.lockAccount();expect(await store.activeAccount()).toBeNull()});
  it('tombstone em conflito conserva a versão autoritativa',async()=>{const s={...session(),rowVersion:2};await store.saveBootstrap(user,bootstrap([s]));await store.saveSession(user,{...s,notes:'local'},device);await store.applyChanges(user,{nextCursor:9,observedRevision:9,hasMore:false,changes:[{revision:9,entityType:'session',entityId:s.id,entityVersion:9,changeKind:'delete',payloadJson:null}]});expect((await store.conflicts(user))[0].version).toBe(9)});
});
